apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-configmap
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.app.name }}
data:
  default.conf: |
    server {
      listen 80;

      location / {
      proxy_pass         http://ui-service.ohmyform.svc.cluster.local:5000;
      proxy_redirect     off;
      proxy_set_header   Host $host;
      }

      location  /graphql {
      proxy_pass         http://api-service.ohmyform.svc.cluster.local:5000;
      proxy_redirect     off;
      proxy_set_header   Host $host;
      }
    }