apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.app.name }}
type: {{ .Values.secret.type }}
data:
  POSTGRES_PASSWORD: {{ .Values.secret.data.pwd }}